= Laboreinheit: Algorithmen und Datenstrukturen - Aufgabenblatt X
Tom Kamberg-Buhrtz <buhrtz@htw-berlin.de>

:stem: latexmath

== Aufgaben

.Built-in
asciidoctor-version:: {asciidoctor-version}
safe-mode-name:: {safe-mode-name}
docdir:: {docdir}

[plantuml, diagram-classes, svg]
....

class Console {
     {static} +int readIntegerFromStdin(String text)
     {static} +String readStringFromStdin(String text)
}
note right: Klasse für das Einlesen von Ganzzahlen\n und Strings vom Stdin.

class CommandFactory {
    +ICommand createGCDSubRecCmd()
    +ICommand createGCDSubItCmd()
    +ICommand createGCDDivRestRecCmd()
    +ICommand createGCDDivRestIteCmd()
}

interface ICommand {
    + execute()
    + toString()
}
note right: Schnittstellenklasse für \ndie Verarbeitung\n von diversen Befehlen

class GCDSubRecCmd{
    + execute()
    + toString()
}
note top: Schnittstellenklasse für \ndie Verarbeitung\n von diversen Befehlen

class GCDSubItCmd{
    + execute()
    + toString()
}
class GCDDivRestRecCmd{
    + execute()
    + toString()
}
class GCDDivRestIteCmd {
    + execute()
    + toString()
}
GCDDivRestIteCmd *-- Console : use
GCDDivRestRecCmd *-- Console : use
GCDSubItCmd      *-- Console : use
GCDSubRecCmd     *-- Console : use

CommandFactory <|- ICommand
ICommand <|-- GCDSubRecCmd
ICommand <|-- GCDSubItCmd
ICommand <|-- GCDDivRestRecCmd
ICommand <|-- GCDDivRestIteCmd
....

https://plantuml.com/de/class-diagram

https://plantuml.com/de/skinparam



[ditaa, "ditaa-diagram", svg]
....
                   +-------------+
                   | Asciidoctor |-------+
                   |   diagram   |       |
                   +-------------+       | PNG out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /---------------\
 |        | --+ Asciidoctor +--> |               |
 |  Text  |   +-------------+    |   Beautiful   |
 |Document|   |   !magic!   |    |    Output     |
 |     {d}|   |             |    |               |
 +---+----+   +-------------+    \---------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+
....



[plantuml, diagram-classes2, svg]
....

skinparam monochrome true

actor User
participant "First Class" as A
participant "Second Class" as B
participant "Last Class" as C

User -> A: DoWork
activate A

A -> B: Create Request
activate B

B -> C: DoWork
activate C
C --> B: WorkDone
destroy C

B --> A: Request Created
deactivate B

A --> User: Done
deactivate A

....

A matrix can be written as stem:[[[a,b\],[c,d\]\]((n),(k))].


latexmath:[$C = \alpha + \beta Y^{\gamma} + \epsilon$]

asciimath:[x/x={(1,if x!=0),(text{undefined},if x=0):}]

latexmath:[$\sum_{n=1}^\infty \frac{1}{2^n}$]

[stem]
++++
sqrt(4) = 2
++++

[stem]
++++
	G = \{V, \vec{X}\}

	V = \{1, 2, 3, 4, 5\}

	\vec{X} = \{(1, 2), (2, 3), (3, 4), (5, 1), (1, 3), (2, 5), (3, 5), (4, 5)\}
++++

[asciimath]
++++
G = \{V, \vec{X}\}

V = \{1, 2, 3, 4, 5\}

\vec{X} = \{(1, 2), (2, 3), (3, 4), (5, 1), (1, 3), (2, 5), (3, 5), (4, 5)\}
++++

[latexmath]
++++
G = \{V, \vec{X}\}\\
V = \{1, 2, 3, 4, 5\}\\
\vec{X} = \{(1, 2), (2, 3), (3, 4), (5, 1), (1, 3), (2, 5), (3, 5), (4, 5)\}\\
++++

.Matrix[latexmath]
++++++++++++++++++++++++++++++++++++++++++++
\[ P^{e \rightarrow c}= \left[\begin{array}{*{3}{r@{}l}}& \cos \theta & & \sin \theta \sin \varphi & & \sin \theta \cos \varphi\\& \sin \theta \sin \psi& & \cos \varphi \cos \psi - \cos \theta \sin \varphi \sin \psi& - & \sin \varphi \cos \psi - \cos \theta \cos \varphi \sin \psi\\- & \sin \theta \cos \psi& & \cos \varphi \sin \psi + \cos \theta \sin \varphi \cos \psi& - & \sin \varphi \sin \psi + \cos \theta \cos \varphi \cos \psi\\\end{array}\right] \]
++++++++++++++++++++++++++++++++++++++++++++


The formula $a^2 + b^2 = c^2$ relates the sides
and hypotenuse of a right triangle.  The formula
\[
\int_0^1 x^n dx = \frac{1}{n+1}
\]
is something we all learn in Calculus

[env.theorem]
--
The Diophantine equation
\[
x^n + y^n = z^n
\]
for $n > 2$ has only trivial solutions
--


[bibliography]
== References

bibliography::[]


- [[[pp]]] Andy Hunt & Dave Thomas. The Pragmatic Programmer:
From Journeyman to Master. Addison-Wesley. 1999.
- [[[gof,2]]] Erich Gamma, Richard Helm, Ralph Johnson & John Vlissides. Design Patterns:
Elements of Reusable Object-Oriented Software. Addison-Wesley. 1994.


[graphviz, diagram-class-console1, svg]
....
strict graph {
  a -- b
  a -- b
  b -- a [color=blue]
}
....


https://github.com/hibernate/hibernate-orm/blob/master/documentation/documentation.gradle#L236-L257

https://powerman.name/doc/asciidoc

https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/_includes/image-sizing.adoc