= Laboreinheit: Algorithmen und Datenstrukturen - Aufgabenblatt 2 (DRAFT)

CAUTION: Zum Lösen der Aufgabe verwenden Sie bitte die Standarddatentypen und –definition von JAVA. LinkedList,
         ArrayList usw. dürfen nicht verwendet werden.

== Aufgaben

. Erarbeitung einer einfach verketteten Liste

.. Erarbeiten Sie sich die notwendige Datenstruktur einer einfach verketteten Liste
.. Zu speichern in unserer Liste sind Studenten mit Vor- und Nachnamen nebst Matrikelnummer und Studiengang. Entwerfen Sie die notwendigen Datentypen und begründen Sie gegebenenfalls Ihre Wahl.
.. Implementieren Sie die notwendigen Datentypen in JAVA unter Verwendung von \texttt{class}, \texttt{interface}, \texttt{enum}  und den entsprechenden gewählten Datentypen.


. Funktionalität zur Verarbeitung von Elementen einer einfach verketteten Liste

.. Implementieren Sie eine Funktion zum Erstellen eines neuen Elements.
.. Implementieren Sie eine Funktion zum Hinzufügen eines Elements vor dem ersten Element.
.. Implementieren Sie eine Funktion zum Hinzufügen eines Elements nach dem letzten Element.
.. Implementieren Sie eine Funktion zur Ausgabe eines Elements der Liste.
.. Implementieren Sie eine Funktion zur Ausgabe der gesamten Liste.
.. Implementieren Sie eine Funktion zur Ausgabe der Anzahl der Elemente.
.. Implementieren Sie eine Funktion zum Löschen eines Elements.
.. Implementieren Sie eine Funktion zum Löschen der gesamten Liste.
.. Implementieren Sie Funktionalität zum Suchen eines oder mehrerer Studenten nach Vor- und Nachname, Matrikelnummer und Studiengang.
.. Implementieren Sie Funktionalität zum Sortieren der Datensätze der Studenten, Matrikelnummer und Studiengang nach zwei selbstgewählten Sortierverfahren.

. Einige Methoden obiger einfach verketteter Liste lassen sich (im Gegensatz zum Array oder einer doppelt verketteten Liste) effizient (in unterschiedlicher Hinsicht) implementieren, andere nicht unbedingt - welche sind das und warum?

. Implementieren Sie obige Datenstruktur und 4 der oben genannten Funktionalitäten (möglichst laufzeiteffizienter) als doppelt verkettete Liste.

. Analysieren Sie die Komplexität der von ihnen implementierten Sortierverfahren allgemein und im speziellen Fall Ihrer Implementierung.

== Deadline und Punkte

.Maximale Punkte und Deadline
|===
|*Deadline:*               | *16.04.2020*
|*Maximale ZKP:*           | *3 ZKP (Zusätzlicher Klausur Punkt)*
|*Maximale Punktanzahl:*   | *64 Punkte* == *100 %* == *3 ZKP*
|===

NOTE: Wird die volle Punktzahl beim Aufgabenblatt erreicht, dann haben Sie *100 %* erfüllt und somit einen *3 ZKP * 1.0 = 3 ZKP*.
Haben Sie nur *50 %* erfüllt, dann berechnet sich der zusätzliche Klausurpunkt, wie folgt  *3 ZKP * 0.5 = 1.5 ZKP*
usw.

== Hinweis

Bei jeder Abgabe muss der Gradle-Wrapper `gradlew` im Projektrootverzeichnis vorhanden sein und funktionieren,
sonst wird keine Bewertung der Aufgabe vorgenommen. Es dürfen nur relative Pfade verwendet werden.
Die folgenden Task müssen per Command-line im Projektrootverzeichnis ausführbar sein:

[source,bash]
----
./gradlew clean         Löscht alle generierten Dateien.
./gradlew build         Programm bauen.
./gradlew test          Programm testen.
./gradlew check         Checks.
./gradlew javadoc       JavaDoc erstellen.
----

TIP: Verwalten Sie den Source Code über die Versionsverwaltung Git als Übung für zukünftige Projekte in der AI.



== Feedback

*Senden Sie mir gerne konstruktives Feedback zu den Aufgabenblättern und Dokumenten zu.* Diese Ausarbeitung sind relativ Neu!

CAUTION: Verbesserungvorschläge für dieses Aufgabenblatt können Sie gerne per Git-Patch oder E-Mail an mich senden.
Git-Patches geben Ihnen die Möglichkeit zusätzliche Punkte für ein Aufgabenblatt zu erhalten, dafür müssen die
Git-Patches atomar sein und im ZIP-Archive abgelegt werden.

Viel Spass und Erfolg bei der Entwicklung der Java-Konsolenanwendungen.

== Referenzen

. http://openbook.rheinwerk-verlag.de/javainsel9[Openbook: Java ist auch eine Insel]
.. http://openbook.rheinwerk-verlag.de/javainsel9/javainsel_05_008.htm[Java ist auch eine Insel - Kapitel Vererbung]
. https://www.w3schools.com/java/java_interface.asp[JAVA Interfaces]
. https://gradle.org[Gradle]
.. https://gradle.org/install/[Gradle Installation]
.. https://gradle.org/guides/[Gradle Tutorials and Guides]
. https://git-scm.com/[Git]
.. https://git-scm.com/book/en/v2[Pro Git Book - Englisch (PDF etc.)]
.. https://git-scm.com/book/de/v2[Pro Git Book - Deutsch]
. http://junit.org[JUnit-Testframework]
. https://studi.f4.htw-berlin.de/www/[HTW Berlin - Projekteserver]
